packages:
  - "web"
  - "studio"
overrides:
  form-data: 4.0.6
  smol-toml: 1.7.1
  js-yaml: 3.15.2
  uuid: 11.1.1
  adm-zip: 0.6.1
minimumReleaseAge: 10080
blockExoticSubdeps: true
# Ignore trust policy assuming they are safe due to their age
trustPolicyIgnoreAfter: 10080
allowBuilds:
  esbuild: false
