packages:
  - "web"
  - "studio"
minimumReleaseAge: 10080
blockExoticSubdeps: true
# Ignore trust policy assuming they are safe due to their age
trustPolicyIgnoreAfter: 10080
allowBuilds:
  esbuild: false
