name: 'Add issue to Github release note on PR merge'

on:
  pull_request_target:
    types:
      - closed

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: 'COMMIT'
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}",
              "categories": [
                {
                    "title": "## 🚀 Features",
                    "labels": ["feature"]
                  },
                  {
                    "title": "## 🐛 Fixes",
                    "labels": ["fix"]
                  },
                {
                    "title": "## Other",
                    "labels": []
                }
              ],
              "sort": {
              "order": "ASC",
              "on_property": "mergedAt"
                },
              "label_extractor": [
                {
                  "pattern": "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                  "target": "$1"
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
